

namespace PS5000A
{
    partial class PS5000ABlockForm
    {
        private System.ComponentModel.IContainer components = null;

        
        //true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        
        //private System.Windows.Forms.Button buttonOpen;
        //private System.Windows.Forms.TabControl tabControl;
        //private System.Windows.Forms.TabPage tabUnit;
        //private System.Windows.Forms.TabPage tabChannels;
        //private System.Windows.Forms.ComboBox comboRangeA;
        //private System.Windows.Forms.TabPage tabAbout;
        //private System.Windows.Forms.TextBox textBoxUnitInfo;
        //private System.Windows.Forms.ComboBox comboRangeB;
        //private System.Windows.Forms.ComboBox comboRangeC;
        //private System.Windows.Forms.ComboBox comboRangeD;
        //private System.Windows.Forms.TabPage tabGetData;
        //private System.Windows.Forms.TextBox textData;
        //private System.Windows.Forms.Button buttonStart;
        //private System.Windows.Forms.TextBox textMessage;
        //private System.Windows.Forms.Label label1;
        //private System.Windows.Forms.TextBox textBox1;
        //private System.Windows.Forms.TextBox textBox7;
        //private System.Windows.Forms.Label label10;
        //private System.Windows.Forms.Label label11;
        //private System.Windows.Forms.Label label12;
        //private System.Windows.Forms.TextBox textBox8;
        //private System.Windows.Forms.TextBox textBox5;
        //private System.Windows.Forms.Label label7;
        //private System.Windows.Forms.Label label8;
        //private System.Windows.Forms.Label label9;
        //private System.Windows.Forms.TextBox textBox6;
        //private System.Windows.Forms.TextBox textBox3;
        //private System.Windows.Forms.Label label4;
        //private System.Windows.Forms.Label label5;
        //private System.Windows.Forms.Label label6;
        //private System.Windows.Forms.TextBox textBox4;
        //private System.Windows.Forms.TextBox textBox2;
        //private System.Windows.Forms.Label label3;
        //private System.Windows.Forms.Label label2;
        //private System.Windows.Forms.GroupBox groupBox1;
        //private System.Windows.Forms.StatusStrip statusStrip1;
        //private System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabel1;
        //private System.Windows.Forms.ToolStripProgressBar toolStripProgressBar1;
        //private System.Windows.Forms.Timer timer1;
        private System.Windows.Forms.TabControl tabControl1;
        private System.Windows.Forms.TabPage tabPage1;
        private System.Windows.Forms.Button button1;
        private System.Windows.Forms.TabPage tabPage2;
        private System.Windows.Forms.Button button2;
        private System.Windows.Forms.TextBox textBox9;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.ComboBox comboRangeA;
        private System.Windows.Forms.ProgressBar progressBar1;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Timer timer1;
        private System.Windows.Forms.TextBox textBox14;
        private System.Windows.Forms.Label label21;
        private System.Windows.Forms.TextBox textBox13;
        private System.Windows.Forms.Label label20;
        private System.Windows.Forms.Label label15;
        private System.Windows.Forms.TextBox textBox11;
        private System.Windows.Forms.TextBox textBox10;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.CheckBox checkBox1;
        private System.Windows.Forms.TabPage tabPage3;
        private System.Windows.Forms.TabPage tabPage4;
        private System.Windows.Forms.TabPage tabPage5;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Button button5;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Button button4;
        private System.Windows.Forms.Button button3;
        private System.Windows.Forms.Label label16;
        private System.Windows.Forms.TextBox textBox1;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.TabPage tabPage6;
        private System.Windows.Forms.ListBox listBox1;
        private System.Windows.Forms.Button button7;
        private System.Windows.Forms.Button button6;
        private System.Windows.Forms.TextBox textBoxUnitInfo;
        private System.Windows.Forms.Button button8;
        private System.Windows.Forms.CheckBox checkBox20;
        private System.Windows.Forms.Button button10;
        private System.Windows.Forms.TextBox textBox2;
        private System.Windows.Forms.Button button9;
        private System.Windows.Forms.Button button11;
        private System.Windows.Forms.CheckedListBox checkedListBox2;
        private System.Windows.Forms.CheckedListBox checkedListBox1;
        private System.Windows.Forms.CheckBox checkBox2;
        private System.Windows.Forms.Label label17;
        private System.Windows.Forms.TextBox textBox3;
        private System.Windows.Forms.CheckBox checkBox4;
        private System.Windows.Forms.CheckBox checkBox3;
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.CheckBox checkBox6;
        private System.Windows.Forms.CheckBox checkBox5;
        private System.Windows.Forms.TextBox textBox6;
        private System.Windows.Forms.TextBox textBox5;
        private System.Windows.Forms.TextBox textBox4;
        private System.Windows.Forms.Label label22;
        private System.Windows.Forms.Label label19;
        private System.Windows.Forms.Label label18;
        private System.Windows.Forms.Button button12;
        private System.Windows.Forms.TextBox textBox8;
        private System.Windows.Forms.Label label24;
        private System.Windows.Forms.Label label23;
        private System.Windows.Forms.TextBox textBox7;
        private System.Windows.Forms.CheckBox checkBox7;
        private System.Windows.Forms.TextBox textBox12;
        private System.Windows.Forms.Label label25;
        private System.Windows.Forms.TextBox textBox16;
        private System.Windows.Forms.CheckBox checkBox9;
        private System.Windows.Forms.TextBox textBox15;
        private System.Windows.Forms.CheckBox checkBox8;
        private System.Windows.Forms.CheckBox checkBox10;
        private System.Windows.Forms.TextBox textBox17;
        private System.Windows.Forms.Button button13;
        private System.Windows.Forms.TextBox textBox18;
        private System.Windows.Forms.CheckBox checkBox11;
        private System.Windows.Forms.CheckBox checkBox12;
        private System.Windows.Forms.CheckBox checkBox13;
        private System.Windows.Forms.Label label26;
        private System.Windows.Forms.TextBox textBox19;
        private System.Windows.Forms.Label label27;
        private System.Windows.Forms.Label label28;
        private System.Windows.Forms.TextBox textBox20;
        private System.Windows.Forms.Button button14;
        private System.Windows.Forms.FolderBrowserDialog folderBrowserDialog1;
        private System.Windows.Forms.DataVisualization.Charting.Chart chart1;
        private System.Windows.Forms.TabPage tabPage7;
        private System.Windows.Forms.Label label30;
        private System.Windows.Forms.TextBox textBox21;
        private System.Windows.Forms.TabPage tabPage8;
        private System.Windows.Forms.Button button15;
        private System.Windows.Forms.Button button16;
        private System.Windows.Forms.TabPage tabPage9;
        private System.Windows.Forms.CheckBox checkBox14;
        private System.Windows.Forms.Button button17;
        private System.Windows.Forms.Label label29;
        private System.Windows.Forms.TextBox textBox22;
        private System.Windows.Forms.TabPage tabPage10;
        private System.Windows.Forms.TextBox textBox25;
        private System.Windows.Forms.Label label33;
        private System.Windows.Forms.TextBox textBox24;
        private System.Windows.Forms.Label label32;
        private System.Windows.Forms.TextBox textBox23;
        private System.Windows.Forms.Label label31;
        private System.Windows.Forms.Button button18;
        private System.Windows.Forms.ListBox listBox2;
        private System.Windows.Forms.Button button19;
        private System.Windows.Forms.Button button20;
        private System.Windows.Forms.TextBox textBox26;
        private System.Windows.Forms.Button button21;
        private System.Windows.Forms.TextBox textBox27;
        private System.Windows.Forms.Timer timer2;
        private System.Windows.Forms.Label label34;
        private System.Windows.Forms.Button button25;
        private System.Windows.Forms.Button button24;
        private System.Windows.Forms.Button button23;
        private System.Windows.Forms.Button button22;
        private System.Windows.Forms.TextBox textBox28;
        private System.Windows.Forms.Label label35;
        private System.Windows.Forms.TextBox textBox29;
        private System.Windows.Forms.Label label36;
        private System.Windows.Forms.TabPage tabPage11;
        private System.Windows.Forms.Button button26;
        private System.Windows.Forms.TextBox textBox34;
        private System.Windows.Forms.Label label41;
        private System.Windows.Forms.TextBox textBox35;
        private System.Windows.Forms.Label label42;
        private System.Windows.Forms.TextBox textBox32;
        private System.Windows.Forms.Label label39;
        private System.Windows.Forms.TextBox textBox33;
        private System.Windows.Forms.Label label40;
        private System.Windows.Forms.TextBox textBox30;
        private System.Windows.Forms.Label label37;
        private System.Windows.Forms.TextBox textBox31;
        private System.Windows.Forms.Label label38;
        private System.Windows.Forms.CheckBox checkBox15;
        private System.Windows.Forms.TextBox textBox36;
        private System.Windows.Forms.Label label43;
        private System.Windows.Forms.TextBox textBox37;
        private System.Windows.Forms.Label label44;
        private System.Windows.Forms.TextBox textBox38;
        private System.Windows.Forms.Label label45;
        private System.Windows.Forms.CheckBox checkBox17;
        private System.Windows.Forms.CheckBox checkBox16;
    }
}

