name: "full_pipeline"
broker: "127.0.0.1:7912"

sources:
  - name: gen_chA
    type: synth
    params:
      waveform: sweep
      chirp_f1: 300
      chirp_f2: 3000
      sweep_period: 10
      amplitude: 1.0
      topic: raw.gen.chA
      rate: 5

operators:
  - name: fft_gen_chA
    type: fft
    params:
      input_topic: raw.gen.chA
      output_topic: spectrum.gen.chA
      group_id: fft-gen-chA

  - name: stats_gen_chA
    type: stats
    params:
      input_topic: raw.gen.chA
      output_topic: stats.gen.chA
      group_id: stats-gen-chA

  - name: filter_gen_chA
    type: filter
    params:
      input_topic: raw.gen.chA
      output_topic: filtered.gen.chA
      group_id: filter-gen-chA
      low_hz: 800
      high_hz: 2000

  - name: threshold_gen_chA
    type: threshold
    params:
      input_topic: raw.gen.chA
      output_topic: events.gen.chA
      group_id: threshold-gen-chA
      threshold_mv: 0.8
