name: "multi_signal"
broker: "127.0.0.1:7912"

sources:
  - name: gen_chA
    type: synth
    params:
      waveform: sweep
      chirp_f1: 200
      chirp_f2: 4000
      sweep_period: 8
      amplitude: 1.0
      topic: raw.gen.chA
      rate: 5
      channel_id: 0

  - name: gen_chB
    type: synth
    params:
      waveform: sweep
      chirp_f1: 500
      chirp_f2: 6000
      sweep_period: 5
      amplitude: 0.8
      topic: raw.gen.chB
      rate: 5
      channel_id: 1

operators:
  - name: fft_chA
    type: fft
    params:
      input_topic: raw.gen.chA
      output_topic: spectrum.gen.chA
      group_id: fft-gen-chA

  - name: fft_chB
    type: fft
    params:
      input_topic: raw.gen.chB
      output_topic: spectrum.gen.chB
      group_id: fft-gen-chB
